### ISSUE TITLE
Got the same error when reproducing MVXNet on the standard KITTI dataset

### ISSUE THREAD

**Issue by shb9793** [open-mmlab/mmdetection3d#1613]
No matter what learning rate I use, the training of MVXNet breaks at some epoch and the error reported at the end is **the same as below**. Such a problem will occur regardless of batchsize=1 or batchsize=2. Before this, I have successfully trained Pointpillars on the standard KITTI dataset. The environment configuration may not be the source of the problem.

```ruby
2022-07-07 21:11:18,047 - mmdet - INFO - Epoch [1][4250/7424]	lr: 3.000e-04, eta: 14:30:08, time: 0.174, data_time: 0.003, memory: 3576, loss_cls: 0.4406, loss_bbox: 0.7178, loss_dir: 0.1037, loss: 1.2621, grad_norm: 14.8252
2022-07-07 21:11:26,896 - mmdet - INFO - Epoch [1][4300/7424]	lr: 3.000e-04, eta: 14:29:54, time: 0.177, data_time: 0.003, memory: 3576, loss_cls: 0.3385, loss_bbox: 0.6383, loss_dir: 0.0931, loss: 1.0700, grad_norm: 19.2091
2022-07-07 21:11:35,544 - mmdet - INFO - Epoch [1][4350/7424]	lr: 3.000e-04, eta: 14:29:27, time: 0.173, data_time: 0.003, memory: 3576, loss_cls: 0.3948, loss_bbox: 0.7311, loss_dir: 0.1155, loss: 1.2414, grad_norm: 15.1344
2022-07-07 21:11:44,337 - mmdet - INFO - Epoch [1][4400/7424]	lr: 3.000e-04, eta: 14:29:10, time: 0.176, data_time: 0.003, memory: 3576, loss_cls: 0.3524, loss_bbox: 0.6662, loss_dir: 0.1076, loss: 1.1262, grad_norm: 15.9612
Traceback (most recent call last):
  File "tools/train.py", line 265, in <module>
    main()
  File "tools/train.py", line 254, in main
    train_model(
  File "/data/run01/scz3687/openmmlab/mmdetection3d/mmdet3d/apis/train.py", line 344, in train_model
    train_detector(
  File "/data/run01/scz3687/openmmlab/mmdetection3d/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/HOME/scz3687/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/HOME/scz3687/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/HOME/scz3687/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/HOME/scz3687/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/HOME/scz3687/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/HOME/scz3687/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/HOME/scz3687/.conda/envs/openmmlab/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/HOME/scz3687/.conda/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/scatter_points.py", line 51, in backward
    ext_module.dynamic_point_to_voxel_backward(
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Here is my environment configuration:**

```ruby
sys.platform: linux
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /data/apps/cuda/11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0
OpenCV: 4.6.0
MMCV: 1.5.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.0
MMSegmentation: 0.26.0
MMDetection3D: 1.0.0rc3+eb5a5a2
spconv2.0: True
```

**Comment by TLDBN** [comment]
I also encountered this issue,
do you slove this problem?

**Comment by TLDBN** [comment]
I set the learning rate lower at lr=0.0001,it's work for me.

**Comment by shb9793** [comment]
> I set the learning rate lower at lr=0.0001,it's work for me.

Sorry for late reply. I have tried lr=0.0001 and the training process was smooth at the beginning, but it stopped after the fifth epoch. I guess it might have something to do with my computer configuration. My host has a single GPU, but the official training was on 8 GPUs. So the learning rate also needs to be adjusted accordingly.

**Comment by TLDBN** [comment]
My computer hardward and env is same with yours,but my CUDA is 11.6.

**Comment by shb9793** [comment]
> My computer hardward and env is same with yours,but my CUDA is 11.6.

Thanks for your help! I tried to change the learning rate from 0.003 to 0.000375 (0.003/8=0.000375). And it worked totally for 40 epochs.

**Comment by Clichong** [comment]
> > My computer hardward and env is same with yours,but my CUDA is 11.6.
> 
> Thanks for your help! I tried to change the learning rate from 0.003 to 0.000375 (0.003/8=0.000375). And it worked totally for 40 epochs.

It is work! Thanks!
