### ISSUE TITLE
[Bug] PointRCNN CUDA memory keeps increasing during validation

### ISSUE THREAD

**Issue by tony10101105** [open-mmlab/mmdetection3d#1978]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [x] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

<img width="563" alt="螢幕快照 2022-11-02 下午1 07 54" src="https://user-images.githubusercontent.com/43724128/199402962-5df19894-7de5-4eb6-8945-c6fa26823253.png">

### Reproduces the problem - code sample

 I use the original PointRCNN code, with some parameters changed. Code of Data loading/preprocrssing and detector are not changed.

### Reproduces the problem - command or script

I wrote a small bash script:
<img width="385" alt="螢幕快照 2022-11-02 下午1 19 24" src="https://user-images.githubusercontent.com/43724128/199404496-2d2da612-5d1c-4a51-9c57-076e10a9ac47.png">

And then run:
tools/train_singleGPU.sh ./configs/point_rcnn/point_rcnn_2x8_kitti-3d-3classes.py

### Reproduces the problem - error message

Below is just an example of OOM. My Pointrcnn increases for around several MBs per second, so it can be expected that I will get OOM after some time.
<img width="566" alt="螢幕快照 2022-11-02 下午1 12 20" src="https://user-images.githubusercontent.com/43724128/199443550-61b307e5-702c-4c20-ad56-622e40c3359d.png">

### Additional information

Dataset used: KITTI 
Expected result: stable CUDA memory usage during training
When my Pointrcnn starts the training process, the GPU memory keeps increasing slowly (and this will finally cause OOM). However, in the validation process, the memory usage is stable.

I have reproduced other models such as SECOND and Centerpoint, and their memory usage is stable. I'm not sure which part of Poinrcnn module is accumulating the memory usage.

**Comment by chun-hsueh-lee** [comment]
I met similar issue, how did you solve this?

**Comment by JingweiZhang12** [comment]
> I met similar issue, how did you solve this?

Hi. We have fixed it. Please pull the latest code.

**Comment by gynaa** [comment]
Hello, memory still keeps increasing even with the new code. Any advice?

**Comment by jobs9527** [comment]
Hello, memory still keeps increasing even with the new code. Any advice?
