### ISSUE TITLE
"RuntimeError: CUDA error: no kernel image is available for execution on the device" ---- test BEVFusion project

### ISSUE THREAD

**Issue by mynobody** [open-mmlab/mmdetection3d#2439]
# when running the test.py
# python tools/test.py projects/BEVFusion/configs/bevfusion_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py checkpoints/bevfusion_converted.pth
# 
# Got runtime errors
# 
# Loads checkpoint by local backend from path: checkpoints/bevfusion_converted.pth
# 04/18 13:57:23 - mmengine - INFO - Load checkpoint from checkpoints/bevfusion_converted.pth
# Traceback (most recent call last):
#   File "tools/test.py", line 130, in <module>
#     main()
#   File "tools/test.py", line 126, in main
#     runner.test()
#   File "/home/cyl/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1752, in test
#     metrics = self.test_loop.run()  # type: ignore
#   File "/home/cyl/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 435, in run
#     self.run_iter(idx, data_batch)
#   File "/home/cyl/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
#     return func(*args, **kwargs)
#   File "/home/cyl/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 454, in run_iter
#     outputs = self.runner.model.test_step(data_batch)
#   File "/home/cyl/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
#     return self._run_forward(data, mode='predict')  # type: ignore
#   File "/home/cyl/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
#     results = self(**data, mode=mode)
#   File "/home/cyl/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
#     return forward_call(*input, **kwargs)
#   File "/home/cyl/mmdetection3d/mmdet3d/models/detectors/base.py", line 86, in forward
#     return self.predict(inputs, data_samples, **kwargs)
#   File "/home/cyl/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 183, in predict
#     feats = self.extract_feat(batch_inputs_dict, batch_input_metas)
#   File "/home/cyl/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 224, in extract_feat
#     pts_feature = self.extract_pts_feat(batch_inputs_dict)
#   File "/home/cyl/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 122, in extract_pts_feat
#     feats, coords, sizes = self.voxelize(points)
#   File "/home/cyl/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
#     return func(*args, **kwargs)
#   File "/home/cyl/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 131, in voxelize
#     ret = self.pts_voxel_layer(res)
#   File "/home/cyl/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
#     return forward_call(*input, **kwargs)
#   File "/home/cyl/mmdetection3d/projects/BEVFusion/bevfusion/ops/voxel/voxelize.py", line 144, in forward
#     return voxelization(
#   File "/home/cyl/mmdetection3d/projects/BEVFusion/bevfusion/ops/voxel/voxelize.py", line 62, in forward
#     voxel_num = hard_voxelize(
# RuntimeError: CUDA error: no kernel image is available for execution on the device
# CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
# For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by JingweiZhang12** [comment]
The voxelization of BEVFusion needs to be re-compiling. https://github.com/open-mmlab/mmdetection3d/blob/main/projects/BEVFusion/README.md

**Comment by sangjinpark97** [comment]
Hi @JingweiZhang12, Do you mean that the current version of BEVFusion doesn't work now?

**Comment by narimanmadani** [comment]
Hi @JingweiZhang12, Training works fine with CUDA11.7 on A100. 
I also get this error when trying to run training on H100 with CUDA11.8 (I have done recompilation for BEVFusion).
This might be a CUDA dependency issue. Do you have any recommendations?

**Comment by liyih** [comment]
@mynobody I am wondering have solved this problem and how do you do that？

**Comment by liyih** [comment]
@sangjinpark97 @narimanmadani @mynobody 
I have solved this problem. It is because the compute capability of your GPU is not match with the projects/BEVFusion/setup.py file. In this file, it only mention:
'-gencode=arch=compute_70,code=sm_70',
'-gencode=arch=compute_75,code=sm_75',
'-gencode=arch=compute_80,code=sm_80',
'-gencode=arch=compute_86,code=sm_86',
this only match some GPUs, whose compute capability is 7.0, 7.5, 8.0, 8.6. For me, I use GTX 1080 Ti, whose compute capability is 6.1. So, I should add '-gencode=arch=compute_61,code=sm_61' in the setup.py file.

**Comment by flstahl** [comment]
Hi,
has there been any update on this? @narimanmadani @JingweiZhang12 @mynobody 

@liyih I think this might work for older GPUs/older compute capability versions. However, when you try this with code=sm_90 (for the NVIDIA H100) this does not seem to do the trick.
