### ISSUE TITLE
Getting "RuntimeError: CUDA error: invalid configuration argument" trying to train MVX-Net

### ISSUE THREAD

**Issue by manonthegithub** [open-mmlab/mmdetection3d#306]
I am getting this trying to train MVX-Net
 `python tools/train.py configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py`

```
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 274, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 54, in extract_pts_feat
    voxels, coors, points, img_feats, img_metas)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/voxel_encoders/voxel_encoder.py", line 274, in forward
    voxel_feats, voxel_coors = self.vfe_scatter(point_feats, coors)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 113, in forward
    points[inds], coors[inds][:, 1:])
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 92, in forward_single
    self.point_cloud_range)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 38, in forward
    coors_range)
RuntimeError: CUDA error: invalid configuration argument
```

the environment:
```
sys.platform: linux
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
CUDA available: True
GPU 0,1: TITAN X (Pascal)
CUDA_HOME: /home/kirilly/cuda10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0+cu101
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.1
MMDetection: 2.9.0
MMDetection3D: 0.10.0+ac9a3e8
```

Did anyone encounter this? What could be the steps for solution?
Thank you a lot in advance for help!

**Comment by ZwwWayne** [comment]
Could you try `dist_train.sh` and see whether it could succeed?

**Comment by manonthegithub** [comment]
@ZwwWayne 
running:
`tools/dist_train.sh configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py 1`
or
`tools/dist_train.sh configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py 2` (I've got 2 GPUs)
gives the same result:
```
2021-02-17 13:41:39,778 - mmdet - INFO - workflow: [('train', 1)], max: 40 epochs
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 46, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 274, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 54, in extract_pts_feat
    voxels, coors, points, img_feats, img_metas)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/voxel_encoders/voxel_encoder.py", line 274, in forward
    voxel_feats, voxel_coors = self.vfe_scatter(point_feats, coors)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 113, in forward
    points[inds], coors[inds][:, 1:])
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 92, in forward_single
    self.point_cloud_range)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 38, in forward
    coors_range)
RuntimeError: CUDA error: invalid configuration argument
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 46, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 274, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 54, in extract_pts_feat
    voxels, coors, points, img_feats, img_metas)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/voxel_encoders/voxel_encoder.py", line 274, in forward
    voxel_feats, voxel_coors = self.vfe_scatter(point_feats, coors)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 113, in forward
    points[inds], coors[inds][:, 1:])
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 92, in forward_single
    self.point_cloud_range)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 38, in forward
    coors_range)
RuntimeError: CUDA error: invalid configuration argument
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/kirilly/mmdetection_env/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/kirilly/mmdetection_env/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Comment by manonthegithub** [comment]
@ZwwWayne maybe you can direct me, what is better to change to make it work? python version? torch version? CUDA version? I can try different configurations

**Comment by ZwwWayne** [comment]
Hi @manonthegithub ,
This is a little bit weird. We will first try to reproduce your bug first and give you feedback.

**Comment by manonthegithub** [comment]
@ZwwWayne thank you! Looking forward to your reply :)

**Comment by zhanggefan** [comment]
Hi, @manonthegithub 

It seems that we encountered the same problem 'CUDA configuration error' two weeks ago. The runtime error was raised when calling a custom PyTorch extension```dynamic_point_to_voxel_forward```. There was a bug in the extension's CUDA part that would lead to runtime error when your points feature being scattered has more than 16 channels.

PR #318  addressing this issue has been merged and this issue should go away with the next release I guess.

If you want more information----------

CUDA configuration error is a kind of kernel launch failure, which is most probably caused by wrongly configured threads number within a CUDA thread block, namely, 'block dim', or wrongly configured blocks number in total, namely 'grid dim'. These numbers are limited by hardware. Especially the block dim, which is limited to 1024 for almost all CUDA GPUs. The upper mentioned extension CUDA code launches (64 * N_feat_channels) threads per block and this is obviously erroneous when N_feat_channels > 16.

Pls check this URL for details https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities

**Comment by manonthegithub** [comment]
@zhanggefan yes looks like the pr may fix the issue, I have changed the num threads in `scatter_points_cuda.cu` on line 17 (`int const threadsPerBlock = sizeof(unsigned long long) * 8;`)
 to 8 instead of 64, and it worked. Putting 16 did not work in my case though.
 @ZwwWayne do you think I made it in a right way? can it somehow affect the results of training?

**Comment by zhanggefan** [comment]
> @zhanggefan yes looks like the pr may fix the issue, I have changed the num threads in `scatter_points_cuda.cu` on line 17 (`int const threadsPerBlock = sizeof(unsigned long long) * 8;`)
> to 8 instead of 64, and it worked. Putting 16 did not work in my case though.
> @ZwwWayne do you think I made it in a right way? can it somehow affect the results of training?

This is indeed a simple and effective workaround!

Looks like your feature channel count was in the range [64, 128), am I right? 

From my point of view, making threadsPerBlock smaller will not affect the training result but it may affect the training speed. This 'scatter points' op has several other kernels and when they are launched with fewer threads per block, which means more blocks to run, the running time would be longer. But the actual performance still depends on the input point cloud size and sometimes the performance decrease may also be neglectable.

**Comment by manonthegithub** [comment]
@zhanggefan thanks for the reply, not sure about the number of features, probably it was as you say

**Comment by manonthegithub** [comment]
@zhanggefan I have checked the latest changes related to #382. Thank you a lot for fixing! The code now fails not in `scatter_points.py`, but in `voxelize.py`. As we already know the problem is in the empty input when `points.shape` is `[0, 4]`. In the `voxelization_cuda.cu`, the `num_points` at the line 193 is 0. Can you please fix that too?
```
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 113, in forward
    self.max_num_points, max_voxels)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 43, in forward
    dynamic_voxelize(points, coors, voxel_size, coors_range, 3)
    ```

**Comment by manonthegithub** [comment]
I am now rechecking it again just to be sure.

**Comment by zhanggefan** [comment]
@manonthegithub I am not familiar with that part (really lots of cuda code there). But I believe Dr.Zhang will help us with it if he has time! ;-) @ZwwWayne

**Comment by manonthegithub** [comment]
@ZwwWayne @zhanggefan 
yep the problem is in the empty input.
I have added ` print("points shape: " + str(points.shape) + "  coors: " + str(coors.shape) + "  voxel size: " + str(voxel_size) + " coors_range: " + str(coors_range))` on the line 43 in `voxelize.py` right before `dynamic_voxelize(points, coors, voxel_size, coors_range, 3)`
And getting the following output: 
```
points shape: torch.Size([8504, 4])  coors: torch.Size([8504, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
[>>>>>>>>>>>                 ] 768/1806, 10.9 task/s, elapsed: 70s, ETA:    95spoints shape: torch.Size([1182, 4])  coors: torch.Size([1182, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
[>>>>>>>>>>>                 ] 769/1806, 10.9 task/s, elapsed: 70s, ETA:    95spoints shape: torch.Size([7767, 4])  coors: torch.Size([7767, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
[>>>>>>>>>>>                 ] 770/1806, 10.9 task/s, elapsed: 70s, ETA:    95spoints shape: torch.Size([0, 4])  coors: torch.Size([0, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
Traceback (most recent call last):
  File "tools/train.py", line 212, in <module>
    main()
  File "tools/train.py", line 208, in main
    meta=meta)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/core/evaluation/eval_hooks.py", line 144, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 60, in forward
    return self.forward_test(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 41, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 404, in simple_test
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 207, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 52, in extract_pts_feat
    voxels, coors = self.voxelize(points)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 38, in voxelize
    res_coors = self.pts_voxel_layer(res)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 114, in forward
    self.max_num_points, max_voxels)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 44, in forward
    dynamic_voxelize(points, coors, voxel_size, coors_range, 3)
RuntimeError: CUDA error: invalid configuration argument
```

**Comment by clytze0216** [comment]
@manonthegithub  I also met this error. How can I solve it? I used the data created myself. Looking forward to your reply. Thanks a lot!

**Comment by manonthegithub** [comment]
@clytze0216 so for me the problem was following:
- when you run create_data.py it generates many things, and one of them is reduced velodyne data (in the folder `<kitti_dataset>/training/velodyne_reduced` and for testing too as I remember)
- in my case some of those velodyne_reduced files were empty (no points in the range), you can just see which files are of 0 bytes size
- the model was failing with the empty input for lidar
- to solve this I just removed those samples from the list of samples for training as well as validation and test (you can find the corresponding files in `<kitti_dataset>/ImageSets/`), and regenerated the infos (`create_data.py`)

Hope that helps! Good luck!

**Comment by aldakata** [comment]
@manonthegithub 
This fix doesn't work, i don't have any empty sample in the velodyn_reduced.

I am running the demo with the model second on a pointcloud of my own like this:
python demo/pcd_demo.py /home/acatalan/Desktop/bin_dir/bin_dir_0/7447458364380.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --show

and I get this error:
  File "demo/pcd_demo.py", line 44, in <module>
    main()
  File "demo/pcd_demo.py", line 31, in main
    result, data = inference_detector(model, args.pcd)
  File "/home/acatalan/Ensemble/mmdetection3d/mmdet3d/apis/inference.py", line 116, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/home/acatalan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/acatalan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/acatalan/Ensemble/mmdetection3d/mmdet3d/models/detectors/base.py", line 61, in forward
    return self.forward_test(**kwargs)
  File "/home/acatalan/Ensemble/mmdetection3d/mmdet3d/models/detectors/base.py", line 42, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/home/acatalan/Ensemble/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 100, in simple_test
    x = self.extract_feat(points, img_metas)
  File "/home/acatalan/Ensemble/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 42, in extract_feat
    voxels, num_points, coors = self.voxelize(points)
  File "/home/acatalan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/acatalan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/acatalan/Ensemble/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 57, in voxelize
    res_voxels, res_coors, res_num_points = self.voxel_layer(res)
  File "/home/acatalan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/acatalan/Ensemble/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 138, in forward
    self.deterministic)
  File "/home/acatalan/Ensemble/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 65, in forward
    deterministic)
RuntimeError: CUDA error: invalid configuration argument


Out of 29 poinclouds I have, 10 of them run with no problem and 19 of them encounter this exception.

What can I do?

**Comment by zhanggefan** [comment]
Hi, @aldakata

Sorry for the late reply.

More information is needed for further troubleshooting.

Could you please try set `deterministic=False` here, and re-run your experiment one more time?

https://github.com/open-mmlab/mmdetection3d/blob/c06c0189a5fe343722722659c9e72230b8283f07/mmdet3d/ops/voxel/voxelize.py#L13-L19

Please let me know if the errors are gone or anything weird happens.
