### ISSUE TITLE
Getting "CUDA error: an illegal memory access was encountered" on MVXNet

### ISSUE THREAD

**Issue by manonthegithub** [open-mmlab/mmdetection3d#382]
Continuing #336

**Describe the bug**
Getting "CUDA error: an illegal memory access was encountered"

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py
```
2. What dataset did you use?
I have used custom dataset converted to kitti format. Training plain kitti dataset works, but with the custom dataset I am getting the error. I have regenerated infos for my dataset.

**Environment**
```
sys.platform: linux
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
CUDA available: True
GPU 0: TITAN X (Pascal)
CUDA_HOME: /home/kirilly/cuda10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0+cu101
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.1
MMDetection: 2.9.0
MMDetection3D: 0.10.0+ac9a3e8
```

**Error traceback**

```
2021-03-04 08:35:26,752 - mmdet - INFO - Epoch [1][50/8195]     lr: 4.323e-04, eta: 1 day, 22:41:33, time: 0.513, data_time: 0.052, memory: 4503, loss_cls: 1.1683, loss_bbox: 2.4333, loss_dir: 0.1463, loss: 3.7479, grad_norm: 113.1708
2021-03-04 08:35:49,141 - mmdet - INFO - Epoch [1][100/8195]    lr: 5.673e-04, eta: 1 day, 19:43:21, time: 0.448, data_time: 0.006, memory: 4523, loss_cls: 0.9347, loss_bbox: 2.0219, loss_dir: 0.1392, loss: 3.0958, grad_norm: 19.0356
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 274, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 54, in extract_pts_feat
    voxels, coors, points, img_feats, img_metas)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/voxel_encoders/voxel_encoder.py", line 244, in forward
    voxel_mean, mean_coors = self.cluster_scatter(features, coors)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 113, in forward
    points[inds], coors[inds][:, 1:])
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 92, in forward_single
    self.point_cloud_range)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 38, in forward
    coors_range)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7fc48ce74536 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x7fc48d0b7fbe in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7fc48ce64abd in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x522fe2 (0x7fc4d4054fe2 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x523086 (0x7fc4d4055086 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: python() [0x54f146]
frame #6: python() [0x588475]
frame #7: python() [0x572b20]
frame #8: python() [0x54ee4b]
frame #9: python() [0x54ee4b]
frame #10: python() [0x588948]
frame #11: python() [0x5ad418]
frame #12: python() [0x5ad42e]
frame #13: python() [0x5ad42e]
frame #14: python() [0x5ad42e]
frame #15: python() [0x5ad42e]
frame #16: python() [0x5ad42e]
frame #17: python() [0x5ad42e]
frame #18: python() [0x56b4c6]
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7fc4e5694bf7 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```

**Comment by manonthegithub** [comment]
@Tai-Wang changing any of the parameters didn't help. Feels like the issue is not about out of memory, but wrong indice or something like that.

I have set the detection range to about 10 times less than it was originally set, the change of voxel size doesn't work either.
I have added a println line in the right before the failing line:
```python 
print("points shape: " + str(points.shape) + "  coors: " + str(coors.shape) + "  voxel size: " + str(voxel_size) + " coors_range: " + str(coors_range))
results = dynamic_point_to_voxel_forward(points, coors, voxel_size,
                                                 coors_range)
```

the output when it fails (the same error as before)
```
points shape: torch.Size([3519, 64])  coors: torch.Size([3519, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3855, 64])  coors: torch.Size([3855, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3519, 128])  coors: torch.Size([3519, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3855, 128])  coors: torch.Size([3855, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4437, 4])  coors: torch.Size([4437, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4316, 4])  coors: torch.Size([4316, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4437, 64])  coors: torch.Size([4437, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4316, 64])  coors: torch.Size([4316, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4437, 128])  coors: torch.Size([4437, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4316, 128])  coors: torch.Size([4316, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4014, 4])  coors: torch.Size([4014, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4462, 4])  coors: torch.Size([4462, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4014, 64])  coors: torch.Size([4014, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4462, 64])  coors: torch.Size([4462, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4014, 128])  coors: torch.Size([4014, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4462, 128])  coors: torch.Size([4462, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4315, 4])  coors: torch.Size([4315, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([743, 4])  coors: torch.Size([743, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
.... stack trace as before
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 40, in forward
    coors_range)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
```

when I am training on the original Kitti dataset I get this output (and it doesn't fail):
```
points shape: torch.Size([18971, 4])  coors: torch.Size([18971, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18345, 64])  coors: torch.Size([18345, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18971, 64])  coors: torch.Size([18971, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18345, 128])  coors: torch.Size([18345, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18971, 128])  coors: torch.Size([18971, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16896, 4])  coors: torch.Size([16896, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18199, 4])  coors: torch.Size([18199, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16896, 64])  coors: torch.Size([16896, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18199, 64])  coors: torch.Size([18199, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16896, 128])  coors: torch.Size([16896, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18199, 128])  coors: torch.Size([18199, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([15517, 4])  coors: torch.Size([15517, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16629, 4])  coors: torch.Size([16629, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([15517, 64])  coors: torch.Size([15517, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16629, 64])  coors: torch.Size([16629, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([15517, 128])  coors: torch.Size([15517, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([16629, 128])  coors: torch.Size([16629, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([20288, 4])  coors: torch.Size([20288, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17393, 4])  coors: torch.Size([17393, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([20288, 64])  coors: torch.Size([20288, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17393, 64])  coors: torch.Size([17393, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([20288, 128])  coors: torch.Size([20288, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17393, 128])  coors: torch.Size([17393, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18793, 4])  coors: torch.Size([18793, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17740, 4])  coors: torch.Size([17740, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18793, 64])  coors: torch.Size([18793, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17740, 64])  coors: torch.Size([17740, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([18793, 128])  coors: torch.Size([18793, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([17740, 128])  coors: torch.Size([17740, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
```

can you give any clue why it may happen? seems like some bug in `scatter_points.py`

**Comment by Tai-Wang** [comment]
I do not find any cues in your error messages that you have reduced the detection range or increased voxel size. Could you also share the config?
Because it works well on KITTI but only triggers errors on your customized dataset, please also check your generated info, maybe you can see when this error is triggered for which sample?

**Comment by manonthegithub** [comment]
@Tai-Wang here are the logs for the run with the original config. But when I change the detection range, the result is the same. I have set even `coors_range: [0, -10, -1, 20, 10, 1]`, and this of course reduced the number of points, but got the same result. In fact you can see that kitty has more points in the samples, therefore should consume more memory. 
I will play with the voxel size more and tell you the results.

**Comment by ZwwWayne** [comment]
I have tried to run the original config on the KITTI dataset and it went well. There might be some issues in your configuration of voxelization that are not compatible with your data.

**Comment by SimonDoll** [comment]
I faced the same issue with my own data but only when using distributed training on more than a single GPU.
Do You have any advice regarding this?
Thanks a lot for any help :+1:

**Comment by manonthegithub** [comment]
@ZwwWayne the configuration is exactly the same for Kitti and my dataset

**Comment by manonthegithub** [comment]
The config file is the same as in the original repo.
```
# model settings
voxel_size = [0.05, 0.05, 0.1]
point_cloud_range = [0, -40, -3, 70.4, 40, 1]

model = dict(
    type='DynamicMVXFasterRCNN',
    img_backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=False),
        norm_eval=True,
        style='caffe'),
    img_neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    pts_voxel_layer=dict(
        max_num_points=-1,
        point_cloud_range=point_cloud_range,
        voxel_size=voxel_size,
        max_voxels=(-1, -1),
    ),
    pts_voxel_encoder=dict(
        type='DynamicVFE',
        in_channels=4,
        feat_channels=[64, 64],
        with_distance=False,
        voxel_size=voxel_size,
        with_cluster_center=True,
        with_voxel_center=True,
        point_cloud_range=point_cloud_range,
        fusion_layer=dict(
            type='PointFusion',
            img_channels=256,
            pts_channels=64,
            mid_channels=128,
            out_channels=128,
            img_levels=[0, 1, 2, 3, 4],
            align_corners=False,
            activate_out=True,
            fuse_out=False)),
    pts_middle_encoder=dict(
        type='SparseEncoder',
        in_channels=128,
        sparse_shape=[41, 1600, 1408],
        order=('conv', 'norm', 'act')),
    pts_backbone=dict(
        type='SECOND',
        in_channels=256,
        layer_nums=[5, 5],
        layer_strides=[1, 2],
        out_channels=[128, 256]),
    pts_neck=dict(
        type='SECONDFPN',
        in_channels=[128, 256],
        upsample_strides=[1, 2],
        out_channels=[256, 256]),
    pts_bbox_head=dict(
        type='Anchor3DHead',
        num_classes=3,
        in_channels=512,
        feat_channels=512,
        use_direction_classifier=True,
        anchor_generator=dict(
            type='Anchor3DRangeGenerator',
            ranges=[
                [0, -40.0, -0.6, 70.4, 40.0, -0.6],
                [0, -40.0, -0.6, 70.4, 40.0, -0.6],
                [0, -40.0, -1.78, 70.4, 40.0, -1.78],
            ],
            sizes=[[0.6, 0.8, 1.73], [0.6, 1.76, 1.73], [1.6, 3.9, 1.56]],
            rotations=[0, 1.57],
            reshape_out=False),
        assigner_per_size=True,
        diff_rad_by_sin=True,
        assign_per_class=True,
        bbox_coder=dict(type='DeltaXYZWLHRBBoxCoder'),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=2.0),
        loss_dir=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.2)))
# model training and testing settings
train_cfg = dict(
    pts=dict(
        assigner=[
            dict(  # for Pedestrian
                type='MaxIoUAssigner',
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                pos_iou_thr=0.35,
                neg_iou_thr=0.2,
                min_pos_iou=0.2,
                ignore_iof_thr=-1),
            dict(  # for Cyclist
                type='MaxIoUAssigner',
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                pos_iou_thr=0.35,
                neg_iou_thr=0.2,
                min_pos_iou=0.2,
                ignore_iof_thr=-1),
            dict(  # for Car
                type='MaxIoUAssigner',
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                pos_iou_thr=0.6,
                neg_iou_thr=0.45,
                min_pos_iou=0.45,
                ignore_iof_thr=-1),
        ],
        allowed_border=0,
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    pts=dict(
        use_rotate_nms=True,
        nms_across_levels=False,
        nms_thr=0.01,
        score_thr=0.1,
        min_bbox_size=0,
        nms_pre=100,
        max_num=50))

# dataset settings
dataset_type = 'KittiDataset'
data_root = 'data/kitti/'
class_names = ['Pedestrian', 'Cyclist', 'Car']
img_norm_cfg = dict(
    mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)
input_modality = dict(use_lidar=True, use_camera=True)
train_pipeline = [
    dict(type='LoadPointsFromFile', coord_type='LIDAR', load_dim=4, use_dim=4),
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True),
    dict(
        type='Resize',
        img_scale=[(640, 192), (2560, 768)],
        multiscale_mode='range',
        keep_ratio=True),
    dict(
        type='GlobalRotScaleTrans',
        rot_range=[-0.78539816, 0.78539816],
        scale_ratio_range=[0.95, 1.05],
        translation_std=[0.2, 0.2, 0.2]),
    dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
    dict(type='PointsRangeFilter', point_cloud_range=point_cloud_range),
    dict(type='ObjectRangeFilter', point_cloud_range=point_cloud_range),
    dict(type='PointShuffle'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle3D', class_names=class_names),
    dict(
        type='Collect3D',
        keys=['points', 'img', 'gt_bboxes_3d', 'gt_labels_3d']),
]
test_pipeline = [
    dict(type='LoadPointsFromFile', coord_type='LIDAR', load_dim=4, use_dim=4),
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1280, 384),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(type='Resize', multiscale_mode='value', keep_ratio=True),
            dict(
                type='GlobalRotScaleTrans',
                rot_range=[0, 0],
                scale_ratio_range=[1., 1.],
                translation_std=[0, 0, 0]),
            dict(type='RandomFlip3D'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(
                type='PointsRangeFilter', point_cloud_range=point_cloud_range),
            dict(
                type='DefaultFormatBundle3D',
                class_names=class_names,
                with_label=False),
            dict(type='Collect3D', keys=['points', 'img'])
        ])
]

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=2,
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file=data_root + 'kitti_infos_train.pkl',
            split='training',
            pts_prefix='velodyne_reduced',
            pipeline=train_pipeline,
            modality=input_modality,
            classes=class_names,
            test_mode=False)),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file=data_root + 'kitti_infos_val.pkl',
        split='training',
        pts_prefix='velodyne_reduced',
        pipeline=test_pipeline,
        modality=input_modality,
        classes=class_names,
        test_mode=True),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file=data_root + 'kitti_infos_val.pkl',
        split='training',
        pts_prefix='velodyne_reduced',
        pipeline=test_pipeline,
        modality=input_modality,
        classes=class_names,
        test_mode=True))
# Training settings
optimizer = dict(type='AdamW', lr=0.003, betas=(0.95, 0.99), weight_decay=0.01)
# max_norm=10 is better for SECOND
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='CosineAnnealing',
    warmup='linear',
    warmup_iters=1000,
    warmup_ratio=1.0 / 10,
    min_lr_ratio=1e-5)
momentum_config = None
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
evaluation = dict(interval=1)
# runtime settings
total_epochs = 40
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = None
# You may need to download the model first is the network is unstable
load_from = 'https://download.openmmlab.com/mmdetection3d/pretrain_models/mvx_faster_rcnn_detectron2-caffe_20e_coco-pretrain_gt-sample_kitti-3-class_moderate-79.3_20200207-a4a6a3c7.pth'  # noqa
resume_from = None
workflow = [('train', 1)]
```

**Comment by manonthegithub** [comment]
I've tried to output the infos, here is the result, running my dataset (I did not find anything suspicious comparing to the original Kitti infos):
```
points shape: torch.Size([4633, 4])  coors: torch.Size([4633, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4633, 64])  coors: torch.Size([4633, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4633, 128])  coors: torch.Size([4633, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
gen info is following: {'sample_idx': '2019-09-11_18-41-27_01530', 'pts_filename': 'data/kitti/training/velodyne_reduced/2019-09-11_18-41-27_01530.bin', 'img_prefix': None, 'img_info': {'filename': 'data/kitti/training/image_2/2019-09-11_18-41-27_01530.png'}, 'lidar2img': array([[ 1.00731561e+03, -2.34756226e+03, -1.06708355e+01,
        -4.81188751e+02],
       [ 4.91165649e+02,  7.62879086e+00, -2.35928906e+03,
        -1.33431018e+03],
       [ 9.99941051e-01,  8.17631464e-03, -7.14315148e-03,
        -6.95557773e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]], dtype=float32), 'ann_info': {'gt_bboxes_3d': LiDARInstance3DBoxes(
    tensor([[ 5.8334e+01,  9.9744e-01, -2.3324e+00,  2.1000e+00,  4.2400e+00,
          1.6100e+00, -1.5710e+00],
        [ 4.3286e+01,  1.0225e+01, -2.6111e+00,  1.8100e+00,  4.3400e+00,
          1.7000e+00, -4.6890e+00],
        [ 6.0752e+01, -7.0636e+00, -2.0216e+00,  1.8800e+00,  4.2400e+00,
          1.5100e+00, -3.0530e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [ 7.1621e+01,  1.5358e+01, -3.2763e+00,  7.4000e-01,  8.7000e-01,
          1.7500e+00,  1.5230e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [ 3.5906e+01,  4.4741e+00, -2.1268e+00,  8.4000e-01,  6.2000e-01,
          1.8300e+00, -8.3000e-02],
        [ 4.5061e+01,  1.5830e+01, -2.4956e+00,  5.2000e-01,  8.5000e-01,
          1.2500e+00, -1.3200e-01],
        [ 4.5878e+01,  1.4927e+01, -2.5627e+00,  5.0000e-01,  8.3000e-01,
          1.2200e+00, -4.2220e+00]])), 'gt_labels_3d': array([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2, -1, -1, -1,  0,  0,  0]), 'bboxes': array([[ 922.96,  500.89, 1010.87,  570.68],
       [ 371.18,  520.58,  517.08,  616.3 ],
       [1200.48,  493.15, 1352.  ,  558.86],
       [ 619.72,  528.58,  684.99,  572.07],
       [ 672.27,  527.21,  735.39,  566.3 ],
       [ 731.09,  522.48,  800.18,  556.23],
       [ 782.98,  515.26,  820.56,  547.85],
       [ 877.08,  509.6 ,  929.63,  553.52],
       [ 970.4 ,  510.49, 1025.05,  553.3 ],
       [1075.3 ,  498.94, 1188.04,  554.13],
       [ 872.25,  488.09,  926.91,  540.45],
       [ 490.67,  526.89,  515.39,  587.05],
       [ 636.51,  517.47,  648.23,  553.36],
       [ 695.14,  482.23,  735.68,  607.14],
       [ 152.09,  537.46,  203.65,  605.35],
       [ 210.16,  541.36,  263.9 ,  604.68]], dtype=float32), 'labels': array([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2, -1, -1, -1,  0,  0,  0]), 'gt_names': array(['Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car', 'Car',
       'Car', 'LargeTruck', 'Obstacle', 'Obstacle', 'Pedestrian',
       'Pedestrian', 'Pedestrian'], dtype='<U10')}}
gen info is following: {'sample_idx': '2018-02-06_15-47-06_00100', 'pts_filename': 'data/kitti/training/velodyne_reduced/2018-02-06_15-47-06_00100.bin', 'img_prefix': None, 'img_info': {'filename': 'data/kitti/training/image_2/2018-02-06_15-47-06_00100.png'}, 'lidar2img': array([[ 1.00731561e+03, -2.34756226e+03, -1.06708355e+01,
        -4.81188751e+02],
       [ 4.91165649e+02,  7.62879086e+00, -2.35928906e+03,
        -1.33431018e+03],
       [ 9.99941051e-01,  8.17631464e-03, -7.14315148e-03,
        -6.95557773e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]], dtype=float32), 'ann_info': {'gt_bboxes_3d': LiDARInstance3DBoxes(
    tensor([[ 5.5317e+01, -2.2986e+00, -1.4857e+00,  1.8300e+00,  4.2300e+00,
          1.7000e+00,  1.0750e+00],
        [ 6.3917e+01,  2.7117e+00, -1.4298e+00,  1.8600e+00,  3.9000e+00,
          1.3900e+00,  1.0390e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [ 7.2017e+01, -1.7434e+01, -7.1745e-01,  2.9200e+00,  2.5580e+01,
          3.5800e+00,  1.3620e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [ 5.1664e+01,  1.4773e+01, -1.9443e+00,  6.3000e-01,  6.8000e-01,
          1.5000e+00, -1.8330e+00],
        [ 5.1869e+01,  1.4145e+01, -1.9667e+00,  6.8000e-01,  8.3000e-01,
          1.7600e+00, -1.8400e+00]])), 'gt_labels_3d': array([ 2,  2,  2, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0]), 'bboxes': array([[1036.9 ,  464.35, 1189.56,  537.62],
       [ 852.53,  477.63,  970.21,  530.62],
       [ 328.36,  487.67,  398.21,  529.21],
       [ 986.93,  425.76, 1167.79,  486.57],
       [1383.43,  365.9 , 1857.05,  495.76],
       [ 191.23,  485.73,  209.38,  531.07],
       [ 218.91,  486.25,  237.92,  531.97],
       [ 264.53,  484.92,  280.13,  531.49],
       [ 282.25,  483.55,  296.73,  534.45],
       [ 482.66,  478.39,  496.79,  516.25],
       [ 526.22,  476.34,  542.26,  517.13],
       [ 547.48,  474.87,  564.56,  517.2 ],
       [ 661.34,  469.93,  678.72,  513.33],
       [ 678.29,  469.93,  694.14,  512.81],
       [ 693.21,  468.67,  710.48,  512.29],
       [1319.99,  444.37, 1334.26,  484.52],
       [ 316.3 ,  494.74,  347.52,  564.09],
       [ 347.5 ,  482.95,  377.4 ,  565.07]], dtype=float32), 'labels': array([ 2,  2,  2, -1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0]), 'gt_names': array(['Car', 'Car', 'Car', 'LargeTruck', 'LargeTruck', 'Pedestrian',
       'Pedestrian', 'Pedestrian', 'Pedestrian', 'Pedestrian',
       'Pedestrian', 'Pedestrian', 'Pedestrian', 'Pedestrian',
       'Pedestrian', 'Pedestrian', 'Pedestrian', 'Pedestrian'],
      dtype='<U10')}}
points shape: torch.Size([3831, 4])  coors: torch.Size([3831, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3831, 64])  coors: torch.Size([3831, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3831, 128])  coors: torch.Size([3831, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
gen info is following: {'sample_idx': '2018-12-10_08-28-20_00000', 'pts_filename': 'data/kitti/training/velodyne_reduced/2018-12-10_08-28-20_00000.bin', 'img_prefix': None, 'img_info': {'filename': 'data/kitti/training/image_2/2018-12-10_08-28-20_00000.png'}, 'lidar2img': array([[ 1.00731561e+03, -2.34756226e+03, -1.06708355e+01,
        -4.81188751e+02],
       [ 4.91165649e+02,  7.62879086e+00, -2.35928906e+03,
        -1.33431018e+03],
       [ 9.99941051e-01,  8.17631464e-03, -7.14315148e-03,
        -6.95557773e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]], dtype=float32), 'ann_info': {'gt_bboxes_3d': LiDARInstance3DBoxes(
    tensor([[ 6.2394e+01, -3.2184e+00, -3.0677e+00,  1.8500e+00,  3.7800e+00,
          1.5700e+00,  9.6800e-01],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00]])), 'gt_labels_3d': array([2, 2]), 'bboxes': array([[1062.31,  531.72, 1199.8 ,  594.63],
       [ 933.42,  537.22,  982.73,  572.43]], dtype=float32), 'labels': array([2, 2]), 'gt_names': array(['Car', 'Car'], dtype='<U3')}}
points shape: torch.Size([4008, 4])  coors: torch.Size([4008, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4008, 64])  coors: torch.Size([4008, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4008, 128])  coors: torch.Size([4008, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
gen info is following: {'sample_idx': '2019-05-02_21-13-56_01920', 'pts_filename': 'data/kitti/training/velodyne_reduced/2019-05-02_21-13-56_01920.bin', 'img_prefix': None, 'img_info': {'filename': 'data/kitti/training/image_2/2019-05-02_21-13-56_01920.png'}, 'lidar2img': array([[ 1.00731561e+03, -2.34756226e+03, -1.06708355e+01,
        -4.81188751e+02],
       [ 4.91165649e+02,  7.62879086e+00, -2.35928906e+03,
        -1.33431018e+03],
       [ 9.99941051e-01,  8.17631464e-03, -7.14315148e-03,
        -6.95557773e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]], dtype=float32), 'ann_info': {'gt_bboxes_3d': LiDARInstance3DBoxes(
    tensor([[14.6655,  4.5903, -1.8746,  0.7500,  0.8700,  1.5800,  1.3550],
        [15.1235,  3.6240, -1.8593,  0.6600,  0.7900,  1.5900,  1.4580],
        [14.6030,  3.7197, -1.8155,  0.3900,  0.2200,  1.2900,  1.4110],
        [13.6441,  3.6617, -1.7187,  0.3400,  0.5200,  0.9500,  1.5050],
        [23.5240,  4.7228, -2.0078,  0.6100,  0.6800,  1.6000,  1.4930]])), 'gt_labels_3d': array([-1,  0,  0,  0,  0]), 'bboxes': array([[188.87, 474.64, 326.38, 745.56],
       [370.89, 469.76, 491.51, 736.25],
       [359.72, 510.52, 430.75, 731.15],
       [339.89, 556.28, 395.45, 723.31],
       [493.06, 489.72, 558.55, 651.41]], dtype=float32), 'labels': array([-1,  0,  0,  0,  0]), 'gt_names': array(['Pedestrian_is_group', 'Pedestrian', 'Pedestrian', 'Pedestrian',
       'Pedestrian'], dtype='<U19')}}
points shape: torch.Size([4043, 4])  coors: torch.Size([4043, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4043, 64])  coors: torch.Size([4043, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4043, 128])  coors: torch.Size([4043, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
gen info is following: {'sample_idx': '2018-12-12_15-21-22_00100', 'pts_filename': 'data/kitti/training/velodyne_reduced/2018-12-12_15-21-22_00100.bin', 'img_prefix': None, 'img_info': {'filename': 'data/kitti/training/image_2/2018-12-12_15-21-22_00100.png'}, 'lidar2img': array([[ 1.00731561e+03, -2.34756226e+03, -1.06708355e+01,
        -4.81188751e+02],
       [ 4.91165649e+02,  7.62879086e+00, -2.35928906e+03,
        -1.33431018e+03],
       [ 9.99941051e-01,  8.17631464e-03, -7.14315148e-03,
        -6.95557773e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]], dtype=float32), 'ann_info': {'gt_bboxes_3d': LiDARInstance3DBoxes(
    tensor([[ 4.9252e+01, -4.6703e-02, -2.3690e+00,  1.9900e+00,  4.2700e+00,
          1.5800e+00, -1.5810e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00]])), 'gt_labels_3d': array([ 2,  2,  2, -1]), 'bboxes': array([[ 966.65,  506.79, 1067.56,  589.7 ],
       [ 820.2 ,  517.39,  874.  ,  556.51],
       [ 856.14,  514.04,  909.09,  550.58],
       [ 941.02,  468.23, 1006.3 ,  550.61]], dtype=float32), 'labels': array([ 2,  2,  2, -1]), 'gt_names': array(['Car', 'Car', 'Car', 'LargeTruck'], dtype='<U10')}}
points shape: torch.Size([4051, 4])  coors: torch.Size([4051, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4051, 64])  coors: torch.Size([4051, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([4051, 128])  coors: torch.Size([4051, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
gen info is following: {'sample_idx': '2018-02-09_17-28-15_00900', 'pts_filename': 'data/kitti/training/velodyne_reduced/2018-02-09_17-28-15_00900.bin', 'img_prefix': None, 'img_info': {'filename': 'data/kitti/training/image_2/2018-02-09_17-28-15_00900.png'}, 'lidar2img': array([[ 1.00731561e+03, -2.34756226e+03, -1.06708355e+01,
        -4.81188751e+02],
       [ 4.91165649e+02,  7.62879086e+00, -2.35928906e+03,
        -1.33431018e+03],
       [ 9.99941051e-01,  8.17631464e-03, -7.14315148e-03,
        -6.95557773e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]], dtype=float32), 'ann_info': {'gt_bboxes_3d': LiDARInstance3DBoxes(
    tensor([[ 9.8486e+00, -3.1194e+00, -1.8315e+00,  1.8500e+00,  4.7700e+00,
          1.4400e+00, -1.5710e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [ 5.9549e+01,  1.3019e+01, -3.3234e+00,  3.6000e-01,  6.2000e-01,
          1.7500e+00, -1.5710e+00],
        [ 6.1218e+01,  1.3053e+01, -3.3853e+00,  4.6000e-01,  6.5000e-01,
          1.5100e+00, -1.7680e+00],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00],
        [ 4.3598e+01, -9.0437e+00, -2.0118e+00,  4.6000e-01,  4.2000e-01,
          1.6500e+00,  2.9100e-01],
        [-1.0003e+03,  9.9041e+02,  1.0082e+03, -1.0000e+00, -1.0000e+00,
         -1.0000e+00, -1.0000e+00]])), 'gt_labels_3d': array([2, 2, 2, 0, 0, 0, 0, 0]), 'bboxes': array([[1498.07,  490.96, 1920.  ,  901.06],
       [ 830.95,  527.73,  866.96,  557.74],
       [1009.02,  530.45, 1043.37,  561.75],
       [ 481.26,  537.2 ,  501.86,  609.35],
       [ 496.07,  549.18,  515.12,  607.39],
       [1244.35,  515.97, 1259.98,  561.73],
       [1494.2 ,  490.22, 1523.11,  584.81],
       [1198.2 ,  525.25, 1214.76,  570.99]], dtype=float32), 'labels': array([2, 2, 2, 0, 0, 0, 0, 0]), 'gt_names': array(['Car', 'Car', 'Car', 'Pedestrian', 'Pedestrian', 'Pedestrian',
       'Pedestrian', 'Pedestrian'], dtype='<U10')}}
points shape: torch.Size([3888, 4])  coors: torch.Size([3888, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3888, 64])  coors: torch.Size([3888, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
points shape: torch.Size([3888, 128])  coors: torch.Size([3888, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
gen info is following: {'sample_idx': '2018-12-21_17-34-11_00300', 'pts_filename': 'data/kitti/training/velodyne_reduced/2018-12-21_17-34-11_00300.bin', 'img_prefix': None, 'img_info': {'filename': 'data/kitti/training/image_2/2018-12-21_17-34-11_00300.png'}, 'lidar2img': array([[ 1.00731561e+03, -2.34756226e+03, -1.06708355e+01,
        -4.81188751e+02],
       [ 4.91165649e+02,  7.62879086e+00, -2.35928906e+03,
        -1.33431018e+03],
       [ 9.99941051e-01,  8.17631464e-03, -7.14315148e-03,
        -6.95557773e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]], dtype=float32), 'ann_info': {'gt_bboxes_3d': LiDARInstance3DBoxes(
    tensor([[ 29.6651,   4.6429,  -1.9919,   1.8700,   3.9200,   1.5700,  -3.4570],
        [ 34.3274, -13.5503,  -1.5421,   1.8500,   4.1600,   1.4600,  -0.7820]])), 'gt_labels_3d': array([2, 2]), 'bboxes': array([[ 468.54,  490.6 ,  811.65,  624.77],
       [1837.  ,  461.58, 1920.  ,  571.19]], dtype=float32), 'labels': array([2, 2]), 'gt_names': array(['Car', 'Car'], dtype='<U3')}}
points shape: torch.Size([968, 4])  coors: torch.Size([968, 3])  voxel size: [0.05, 0.05, 0.1] coors_range: [0, -40, -3, 70.4, 40, 1]
Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 274, in forward_train
    points, img=img, img_metas=img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 208, in extract_feat
    pts_feats = self.extract_pts_feat(points, img_feats, img_metas)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/detectors/mvx_faster_rcnn.py", line 54, in extract_pts_feat
    voxels, coors, points, img_feats, img_metas)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/models/voxel_encoders/voxel_encoder.py", line 244, in forward
    voxel_mean, mean_coors = self.cluster_scatter(features, coors)
  File "/home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 115, in forward
    points[inds], coors[inds][:, 1:])
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 94, in forward_single
    self.point_cloud_range)
  File "/home/kirilly/git_repos/mmdetection3d/mmdet3d/ops/voxel/scatter_points.py", line 40, in forward
    coors_range)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7efe67ae8536 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x7efe67d2bfbe in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7efe67ad8abd in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x522fe2 (0x7efeaecc8fe2 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x523086 (0x7efeaecc9086 in /home/kirilly/v2pearl5p36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: python() [0x54f146]
frame #6: python() [0x588475]
frame #7: python() [0x572b20]
frame #8: python() [0x54ee4b]
frame #9: python() [0x54ee4b]
frame #10: python() [0x588948]
frame #11: python() [0x5ad418]
frame #12: python() [0x5ad42e]
frame #13: python() [0x5ad42e]
frame #14: python() [0x5ad42e]
frame #15: python() [0x5ad42e]
frame #16: python() [0x5ad42e]
frame #17: python() [0x5ad42e]
frame #18: python() [0x56b4c6]
<omitting python frames>
frame #24: __libc_start_main + 0xe7 (0x7efec0308bf7 in /lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by ZwwWayne** [comment]
Hi @manonthegithub ，
Thanks for your bug report. It seems that the error could be reproduced. Could you dump the input of the module that could cause the error and provide it to us? Thus, we could create a tiny unit test to fully reproduce your error and have a check for that. Hopefully, we could solve this bug with the input you provided.

**Comment by manonthegithub** [comment]
@ZwwWayne never did this kind of dumping before. How do I do it? I cant find the core dump (is it the one you mean?) file as well, looked at the directory where I ran python, but there is not such a file, looked in `/var/lib/systemd/coredump/` and it is empty too.

**Comment by Tai-Wang** [comment]
@manonthegithub I guess you can add print commands or set breaking points before the typical dumping point, like scatter_points, to monitor which data triggers the error.

**Comment by tyjiang1997** [comment]
I encounter the same question, and it can be solverd by setting a more voxel numbers

**Comment by Tai-Wang** [comment]
Another possible way to solve it is to reduce the `workers_per_gpu` (from other users' experience). You can also have a try.

**Comment by SimonDoll** [comment]
Thanks a lot for all the help already  :+1: 
I think the bug is related to the combination of pointcloud range and voxel size.
Can you explain how  the sparse_shape is calculated (see code below)? As changing the point cloud range for example triggers the error in the  middle encoder

`    pts_middle_encoder=dict(
        type='SparseEncoder',
        in_channels=128,
        sparse_shape=[41, 1600, 1408],
        order=('conv', 'norm', 'act')),`

**Comment by Tai-Wang** [comment]
Suppose the point cloud range is [0, -40, -3, 70.4, 40, 1], voxel size is [0.05, 0.05, 0.1], then the shape of intermediate feature map is [(1-(-3))/0.1+1, (40-(-40))/0.05, (70.4-0)/0.05]=[41, 1600, 1408]. You can check your sparse_shape in this way.

**Comment by SimonDoll** [comment]
> Suppose the point cloud range is [0, -40, -3, 70.4, 40, 1], voxel size is [0.05, 0.05, 0.1], then the shape of intermediate feature map is [(1-(-3))/0.1+1, (40-(-40))/0.05, (70.4-0)/0.05]=[41, 1600, 1408]. You can check your sparse_shape in this way.

Awesome, thanks a lot!

**Comment by manonthegithub** [comment]
@Tai-Wang @ZwwWayne thank you for the help! I have pulled the latest changes to `scatter_points.py` dated 25 February 2021, and the problem seems gone. At least now, I am getting `RuntimeError: CUDA error: invalid configuration argument` after about 8000 samples in the first epoch. I am continuing to investigate and let you know of the results :).
Thank you a lot again

**Comment by zhanggefan** [comment]
@manonthegithub
Hi! 
> @Tai-Wang @ZwwWayne thank you for the help! I have pulled the latest changes to `scatter_points.py` dated 25 February 2021, and the problem seems gone. At least now, I am getting `RuntimeError: CUDA error: invalid configuration argument` after about 8000 samples in the first epoch. I am continuing to investigate and let you know of the results :).
> Thank you a lot again

I modified `scatter_points.py` on that day and since then the feature-scattering op works in a much different manner.
But that version is already outdated. Could you please try the newer version released on 2nd March?
It is very likely that the problem of `invalid configuration argument` remains after the update (but on my side the debugging would be much easier, haha). Please let me know if it does.

**Comment by manonthegithub** [comment]
@zhanggefan yep, I'm now using the version from March 3. The error is still there. I will am continuing investigation, will report the results soon :).

**Comment by zhanggefan** [comment]
@manonthegithub @Tai-Wang @ZwwWayne 
I managed to reproduce the error by passing empty point (with `feats` size=(0, c) and `coors` size=(0, 3)) into DynamicScatter.
I am really sorry that this op is not yet robust to empty input. I am now working on it.
@manonthegithub
If it is convenient for you, could you please have a check if any empty sample exists in the minibatch when the error raised?
Thanks in advance!

**Comment by manonthegithub** [comment]
@zhanggefan yep, there is an empty input, exactly `feats size =0`. I am trying to figure out which sample causes it to exclude, no luck yet :(. I have checked my data, and it seems to be not empty (will recheck it again), I suppose that it gets empty after filtering out the points from the range (which may be the case for my dataset)

**Comment by manonthegithub** [comment]
the problem is that the main training part is from the other project (just mmdet without 3d), so it makes it more complicated to find the filename of the sample causing the error.

**Comment by zhanggefan** [comment]
@manonthegithub 
I just submit PR #417 fixing this issue. You may have a try in advance. Please let me know it does not work.
Good luck!

**Comment by manonthegithub** [comment]
@zhanggefan thank you a lot for the help! Will run it today and check!

**Comment by ZwwWayne** [comment]
Resolved in #417

**Comment by meanmee** [comment]
> Suppose the point cloud range is [0, -40, -3, 70.4, 40, 1], voxel size is [0.05, 0.05, 0.1], then the shape of intermediate feature map is [(1-(-3))/0.1+1, (40-(-40))/0.05, (70.4-0)/0.05]=[41, 1600, 1408]. You can check your sparse_shape in this way.

That is right，When changing point_cloud_range, remember to change the intermediate feature map according to the voxel size, thanks very much.

**Comment by m-shahbaz-kharal** [comment]
> Suppose the point cloud range is [0, -40, -3, 70.4, 40, 1], voxel size is [0.05, 0.05, 0.1], then the shape of intermediate feature map is [(1-(-3))/0.1+1, (40-(-40))/0.05, (70.4-0)/0.05]=[41, 1600, 1408]. You can check your sparse_shape in this way.

Why there's a +1 in the (1-(-3)/0.1+1)?
