### ISSUE TITLE
CUDA Error in scatter_points

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection3d#908]
I come across the following error in scatter_points_cuda.py when using DynamicVFE (Waymo Dataset):
```
File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mmcv/runner/hooks/optimizer.py", line 259, in after_train_iter
    scaled_loss.backward()
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/mnt/truenas/scratch/mmdet3d/ops/voxel/scatter_points.py", line 46, in backward
    voxel_points_count, ctx.reduce_type)
RuntimeError: CUDA error: an illegal memory access was encountered (dynamic_point_to_voxel_backward_gpu at mmdet3d/ops/voxel/src/scatter_points_cuda.cu:300)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f085e6cd193 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libc10
.so)
frame #1: voxelization::dynamic_point_to_voxel_backward_gpu(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&,
 reduce_t) + 0x144b (0x7f0821a1fba1 in /mnt/truenas/scratch/mmdet3d/ops/voxel/voxel_layer.cpython-36m-x86_64-linux-gnu.so)
frame #2: voxelization::dynamic_point_to_voxel_backward(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, std
::string const&) + 0x78 (0x7f08219ff158 in /mnt/truenas/scratch/mmdet3d/ops/voxel/voxel_layer.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x52b4f (0x7f0821a01b4f in /mnt/truenas/scratch/mmdet3d/ops/voxel/voxel_layer.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x52e5e (0x7f0821a01e5e in /mnt/truenas/scratch/mmdet3d/ops/voxel/voxel_layer.cpython-36m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x57bc1 (0x7f0821a06bc1 in /mnt/truenas/scratch/mmdet3d/ops/voxel/voxel_layer.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #19: torch::autograd::PyNode::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x163 (0x7f08a9cabfe3 in /root/.pyenv/versions/3.6.8/lib/python3.6/
site-packages/torch/lib/libtorch_python.so)
frame #20: <unknown function> + 0x4014ff6 (0x7f0862d3cff6 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #21: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x1373 (0x
7f0862d39453 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #22: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x4b2 (0x7f0862d3a082 in /root/.pyenv/versions/3.6.8/lib/py
thon3.6/site-packages/torch/lib/libtorch.so)
frame #23: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f0862d33979 in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #24: torch::autograd::python::PythonEngine::thread_init(int) + 0x2a (0x7f08a9ca408a in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/lib/libtorch
_python.so)
frame #25: <unknown function> + 0xedef (0x7f08aa8bfdef in /root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #26: <unknown function> + 0x76ba (0x7f08b4bb06ba in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #27: clone + 0x6d (0x7f08b48e641d in /lib/x86_64-linux-gnu/libc.so.6)
NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:65, unhandled cuda error, NCCL version 2.4.8
```

The configuration of VFE is:
```
    pts_voxel_encoder=dict(
        type='DynamicVFE',
        in_channels=3,
        feat_channels=[256],
        with_distance=False,
        voxel_size=voxel_size_list,
        with_cluster_center=True,
        with_voxel_center=True,
        point_cloud_range=point_cloud_range,
        norm_cfg=dict(type='naiveSyncBN1d', eps=1e-3, momentum=0.01)
        # norm_cfg=dict(type='BN1d', eps=1e-3, momentum=0.01)
    ),
```

Environments:
```
sys.platform: linux
Python: 3.6.8 (default, Jul  2 2019, 13:27:03) [GCC 5.4.0 20160609]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.1.0
MMCV: 1.3.8
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.0
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.15.0+e25a9db
```
**Things need to be noticed:**
1. The error is usually raised after hundreds of iterations (around 950~1050), so it might not have something to do with a certain sample.
2. When I use a smaller model (after VFE), the error disappears sometimes, so it seems related to memory limitation. In the log file, memory usage is around 7GB, while the 2080Ti has ~11GB memory. 
3. Since I set CUDA_LAUNCH_BLOCKING to 1, the error information should be accurate (no OOM error raised).

**Comment by zhanggefan** [comment]
Hi, @Abyssaledge 

Did you enable fp16 training? I notice the keyword "scaled_loss" in your log.

Mix precision training with MMDet3D and PyTorch before v1.6 has a lot of weird issues and most of those issues arise from incorrect explicit data type cast in MMCV's fp16 decorators.

**Comment by Abyssaledge** [comment]
@zhanggefan Yes, I enable fp16. I will try a higher version of PyTorch for its native AMP. Thanks a lot for your quick reply.

**Comment by Abyssaledge** [comment]
This problem seems fixed after enabling native fp16 training in PyTorch 1.9.0. 
@zhanggefan Thanks.
